[samba] Fix compile error
WARNING: openvision-enigma2-image-1.0-r0 do_rootfs: samba-common.postinst returned 1, marking as unpacked only, configuration required on target.
ERROR: openvision-enigma2-image-1.0-r0 do_rootfs: Postinstall scriptlets of ['samba-common'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.
Details of the failure are in /home/raed/build_image/920-openvision/openvision-development-platform/build/tmp/work/dm920-oe-linux-gnueabi/openvision-enigma2-image/1.0-r0/temp/log.do_rootfs.
ERROR: Logfile of failure stored in: /home/raed/build_image/920-openvision/openvision-development-platform/build/tmp/work/dm920-oe-linux-gnueabi/openvision-enigma2-image/1.0-r0/temp/log.do_rootfs.23319
ERROR: Task (/home/raed/build_image/920-openvision/openvision-development-platform/meta-openvision/recipes-openvision/images/openvision-enigma2-image.bb:do_rootfs) failed with exit code '1'