enigma2.bb: Remove obsolete python-importlib
ERROR: Nothing RPROVIDES 'python-importlib' (but /home/hains/openvision-development-platform/meta-openvision/
recipes-openvision/enigma2/enigma2.bb RDEPENDS on or otherwise requires it)

Remove -import importlib- from source.