[openvision-enigma2-feed] Remove netatalk from feed recipe
Not compatible with other device such as dreambox. It was braked compile

| ../../../netatalk-2.2.3/bin/afppasswd/afppasswd.c:99:29: error: expected expression before ')' token
|    99 |       ecb_encrypt((C_Block *) buf, (C_Block *) buf, schedule, DES_DECRYPT);
|       |                             ^
| make[3]: *** [Makefile:480: afppasswd.o] Error 1
| make[3]: Leaving directory '/home/raed/build_image/920-openvision/openvision-development-platform/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/netatalk/2.2.3-r0/build/bin/afppasswd'
| make[2]: *** [Makefile:427: all-recursive] Error 1
| make[2]: Leaving directory '/home/raed/build_image/920-openvision/openvision-development-platform/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/netatalk/2.2.3-r0/build/bin'
| make[1]: *** [Makefile:474: all-recursive] Error 1
| make[1]: Leaving directory '/home/raed/build_image/920-openvision/openvision-development-platform/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/netatalk/2.2.3-r0/build'
| make: *** [Makefile:404: all] Error 2
| WARNING: /home/raed/build_image/920-openvision/openvision-development-platform/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/netatalk/2.2.3-r0/temp/run.do_compile.20278:1 exit 1 from 'exit 1'
| 
ERROR: Task (/home/raed/build_image/920-openvision/openvision-development-platform/meta-openvision/recipes-connectivity/netatalk/netatalk_2.2.3.bb:do_compile) failed with exit code '1' 

@persianpros 
You need to add it with use bb.utils.contains for that devices compatible with it .